#!/usr/local/bin/python3
# -*- coding: utf-8 -*-

import re
import sys

import sumologic_opentelemetry

from opentelemetry.instrumentation.bootstrap import run


def check_env():
    print('\n')
    print('> Checking env config:')
    sumologic_opentelemetry.env.generate()
    sumologic_opentelemetry.env.dump()

def install_dependencies():
    print('> Installing dependencies:')
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    return run()

if __name__ == '__main__':
    rc = install_dependencies()
    check_env()
    sys.exit(rc)
