#!/usr/local/bin/python3
# -*- coding: utf-8 -*-

import re
import sys

import sumologic_opentelemetry

from opentelemetry.instrumentation.auto_instrumentation import run


if __name__ == '__main__':
    sumologic_opentelemetry.env.generate()
    sumologic_opentelemetry.env.dump()
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run())